//---------- Mandatory skill's include ----------
#include <pluginlib/class_list_macros.h>//Plugin export library
#include <ros/ros.h>
#include "skiros_skill/skill_base.h"    //Base template for all skills
#include "skiros_common/logger_sys.h"   //Skiros logging system
#include "skiros_config/param_types.h"  //Default parameters
#include "skiros_config/declared_uri.h" //Default world model URIs (Unified Resource Identifier) -> generated by skiros_world_model/generate_uri
//---------- Mandatory skill's include end ----------

namespace skiros_skill
{
using namespace skiros_config::owl;
using namespace skiros_wm;

/*!
 * \brief TODO
 *
 * Teach required: TODO \n
 * Pre-condition: TODO \n
 * Post-condition: TODO \n
 * Additional Params: \n
 *  TODO \n
 * Failures: \n
 *  TODO \n
 *
 */
class Land : public SkillBase
{
public:
    Land()
    {
        this->setSkillType("Drive");
        this->setVersion("0.0.1");
        getParamHandle()->addParamWithDefaultValue("Robot",
                                                  skiros_wm::Element(concept::Str[concept::Robot]),
                                                  "Robot to control",
                                                  skiros_common::online);
        getParamHandle()->addParamWithDefaultValue("Location",
                                                  skiros_wm::Element(concept::Str[concept::Location]),
                                                  "Location to land",
                                                  skiros_common::optional);
    }
    ~Land(){}

    bool onInit()
    {
        addPostcondition("Landed", newCondition("uav:Landed", true, "Robot"));
        addPostcondition("Recharge", newCondition("uav:LowBattery", false, "Robot"));
        return true;
    }

    int preSense()
    {
        return 1;
    }

    int postSense()
    {
        skiros::Module monitor(getModulesHandler(),"monitor_battery", this->moduleType());
        monitor.stop();
        return 1;
    }

    int execute()
    {
        Element landing_location = getParamHandle()->getParamValue<Element>("Location");
        this->setProgress("Landing. ");
        ros::Duration(5.0).sleep(); //Fake an execution time...
        setAllPostConditions();
        return 1;
    }

private:
};

} // namespace

//Export
PLUGINLIB_EXPORT_CLASS(skiros_skill::Land, skiros_skill::SkillBase)
